#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Meta-Builder
Version  : 0.003
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Meta-Builder-0.003.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Meta-Builder-0.003.tar.gz
Summary  : 'Tools for creating Meta objects to track custom metrics.'
Group    : Development/Tools
License  : Artistic-1.0-Perl
BuildRequires : buildreq-cpan
BuildRequires : perl(Fennec::Lite)
BuildRequires : perl(Test::Exception)

%description
NAME
Meta::Builder - Tools for creating Meta objects to track custom metrics.
DESCRIPTION
Meta programming is becomming more and more popular. The popularity of
Meta programming comes from the fact that many problems are made
significantly easier. There are a few specialized Meta tools out there,
for instance <Class:MOP> which is used by Moose to track class metadata.

%package dev
Summary: dev components for the perl-Meta-Builder package.
Group: Development
Provides: perl-Meta-Builder-devel

%description dev
dev components for the perl-Meta-Builder package.


%prep
%setup -q -n Meta-Builder-0.003

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Meta/Builder.pm
/usr/lib/perl5/site_perl/5.26.1/Meta/Builder/Base.pm
/usr/lib/perl5/site_perl/5.26.1/Meta/Builder/Util.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Meta::Builder.3
/usr/share/man/man3/Meta::Builder::Base.3
/usr/share/man/man3/Meta::Builder::Util.3
